language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
script:
  - bash -ex .travis-ocaml.sh
  - opam install -y ocamlnet
  - make
env:
  - OCAML_VERSION=4.02
